name: buss_env
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8
- pytorch
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pillow
- einops
- pip
- pip:
  - torchvision
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
  - transformers
  - fasttext
