name: xnap-example
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8
- pytorch
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pillow
- fasttext
- fasttext.utils
- einops
- pip
- pip:
  - torchvision
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
